"use client";
import "./globals.css";
import { Inter } from "next/font/google";

import Banner from "./Components/Banner/Banner";
import Sidebar from "./Components/Home/Sidebar";
import Navbar from "./Components/Navbar/Navbar";
import { Providers } from "./redux/provider";
import Offcanvas from "./Share/Offcanvas/Offcanvas";
import { useState } from "react";
import MobileFooer from "./Components/Footer/MobileFooer";
import { useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isShow, setIsShow] = useState(false);

  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.className} bg-white w-fulls `}>
          <Navbar isShow={isShow} setIsShow={setIsShow} />
          {children}
          <MobileFooer />
        </body>
      </Providers>
    </html>
  );
}
